app = 'buildr-backend'
primary_region = 'fra'

[http_service]
  internal_port = 4001
  force_https = true
  min_machines_running = 1
  processes = ['app']
  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    path = "/api/health"
    method = "GET"
    timeout = "15s"
    tls_skip_verify = true
    protocol = "http"
    [http_service.checks.headers]
      X-Forwarded-Proto = "https"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "rolling"
